version: 0.2
env:
  secrets-manager:
    DOCKERHUB_PASS: "dockerhub:password"
    DOCKERHUB_USERNAME: "dockerhub:username"

phases:
  pre_build:
    commands:
      - echo pre_build step...
      - echo Logging in to Docker Hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t code-pipeline-automation:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push devopslearnerboy/code-pipeline-automation:latest
